### ISSUE TITLE
Can I use the ShardManager directly, without having to use Navigation AAC? 

### ISSUE THREAD

**Issue by Zhuinden** [evant/android-shard#7]
I'm curious because the wiki doesn't show how to use Shards without it, but it does mention the ability to create a custom host.

**Comment by evant** [comment]
Navigation AAC is the only navigation implementation currently, but you can certainly create your own using another lib or something custom. https://github.com/evant/android-shard/blob/master/docs/hosting-shards.md#custom-host is currently the only documentation on the ShardManager api, I'd say your best bet would be to look at the [source](https://github.com/evant/android-shard/tree/master/shard-nav/src/main/java/me/tatarka/shard/nav).

The concept isn't too complicated, you'd have your own backstack that you can persist.
Moving forward would be done by calling `shardManager.saveState(shard)` and holding on to the result in your backstack, then calling `shardManager.replace(currentShard, newShard, container, transition)` to navigate to the new page. Navigating back would be done by calling `shardManager.restoreState(previousShard, state)` followed by `shardManager.replace(currentShard, previousShard, container, transition)`. The nav impl also has some optimizations so that `replace()` is only called once even if you ex: push on 2 shards in a row but that's up to you if that's important to implement or not.

The goal is for the ShardManager api to be very flexible to be able to used in many use-cases in libs, so I'd love to hear how it goes!

**Comment by evant** [comment]
Working on a simple backstack implementation that can be used directly if you don't want to use Navigation AAC https://github.com/evant/android-shard/pull/23

**Comment by evant** [comment]
There's simple ShardBackStackHost you can use now.
https://github.com/evant/android-shard/blob/master/docs/hosting-shards.md#shardbackstackhost
